### ISSUE TITLE
shutdown system doesn't seems to work

### ISSUE THREAD

**Issue by soravux** [lvsn/CameraNetwork#11]

**Comment by soravux** [comment]
It always worked correctly previously but recently I had a Pi that did not shutdown. I don't know if it is a problem or just a single occurrence because of some glitch...

It may work, if it is the case, just close the ticket. (It was more a reminder for me to check if this was really an issue.)

**Comment by MathGaron** [comment]
Ok I will make some tests and log if something happen

**Comment by soravux** [comment]
Seems to work now.
