### ISSUE TITLE
Stop button is not working

### ISSUE THREAD

**Issue by jacenfox** [lvsn/CameraNetwork#17]
Cannot stop skycam capturing by clicking Stop button in DevicePage.

**Comment by MathGaron** [comment]
What was the state of the camera? I will try to reproduce the bug.

I see many warnings with timelaps services when i launch the server, I'm not sure if it is related...

**Comment by jacenfox** [comment]
It was busy, when the camera start capturing the state is always busy, even in the waiting period (in the 'Frequency' time).

**Comment by MathGaron** [comment]
Ok its the way camera controler is made, it sleep between shots so while it sleep he is unaware of the stop message until he wake up. I will fix this.

**Comment by MathGaron** [comment]
Now it wake up every 2 seconds (so for now the timelaps lose 2 seconds of precision, if it is a problem we can change the resolution or find a more accurate solution)

So when stop is pushed : max 2 sec before the timelaps stops, and 2 sec + refresh rate before GUI turn from busy to idle
