### ISSUE TITLE
"Preview" button not working

### ISSUE THREAD

**Issue by jflalonde** [lvsn/CameraNetwork#20]
Preview button needs to take a picture with the current settings, and display it on the browser window. 
Depends on #16

**Comment by MathGaron** [comment]
Preview image is now more flexible with the type of picture it takes ( tested with jpg and NEF (may work with gif,bmp etc but need to be tested on other raw types))

mjpeg server is still used so all preview picture are send on the same stream. The quality of the pictures are minimum, it just give an average idea, especially for raw, the software use the thumbnail picture wich is ~ 160x120 pixels.
