### ISSUE TITLE
Image capture should let the image in the camera

### ISSUE THREAD

**Issue by soravux** [lvsn/CameraNetwork#8]
Using gphoto2, the image capture function should let the images on the camera SD card while renaming it accordingly.

Then, the download functionality should download the images from the camera yo the server.

**Comment by MathGaron** [comment]
Thinking about it, the way that pictures are named should be changed, it would be more appropriate to name them at capture time. Then it would simplify this problem to only find a way to call load_picture at the right time.

**Comment by soravux** [comment]
You are right. I've removed the auto-download which was by default in commit 640c2b6. I planned the image name will be set by the exif tag in the image by a script later on. I'll create a new ticket for this.
